CHANGELOG.md, README.md, index.d.ts, index.js, mobx-react-custom.patch, mobx-react-native.patch, package.json, test/context.js, test/ts/compile-ts.tsx
MobX can now pass stores around via context! Use `Provider` to provide them, and `@observer([store names])` to make them available in your component's props
Beta build is available: `3.4.0-beta.1`
Docs: https://github.com/mobxjs/mobx-react/blob/provider/README.md#provider-experimental
=> Introducing Provider, implements #53

index.js
I just added checks before using the componentByNodeRegistry variable. Not sure how devtools will handle the case that it's undefined.
=> Fixed #66 - Doesn't work in IE 10

index.js
Do not run "forceUpdate()" if the component has *not* been mounted. Fixes Server Side Rendering of a component marked as @observer with React 15.0
=> fixes issue with React 15 - React DOM tree root should always have a node reference.

src/propTypes.js
As per the react docs for libraries:
https://facebook.github.io/react/warnings/dont-call-proptypes.html#fixing-the-false-positive-in-third-party-proptypes
Note that I was unable to compile / test this. I had all sorts of issues with `npm link`ing it, and it then failing on `thing instanceof ObservableArray`. In the end, I hacked this into the already-compiled source of the `npm install`d version in my repo, and verified it still worked.
Please test this thoroughly with your normal build process and react@latest.
=> Pass 'secret' PropType argument to disable warning

src/index.js
I think, that's more intuitive for react users?
=> Export propTypes as PropTypes

.gitignore, .travis.yml, package.json, test/browser/index.html, test/context.js, test/inject.js, test/issue21.js, test/misc.js, test/observer.js, test/propTypes.js, test/stateless.js, test/transactions.js, test/utilities.js
Solve issue [#155](https://github.com/mobxjs/mobx-react/issues/155):
Add support of `es6` and `react` to tests and refactor them. 
Also add ability to build tests bundle and run it in browser: `npm run test:build`
@mweststrate please review
The next step to rewrite `jquery` to `enzyme` from some tests file.
=> Issue #155 - ES6 Test support

src/index.d.ts
Just found out that the order of the type definitions I added (v4.0.1) is not right. Something to do with specificity as far as I can see. Didn't work as intended before. Does work with this PR.
(I hadn't found out earlier because I had tested them as a merged declaration, in which new definitions are _prepended_ the existing ones I suppose.)
Sorry!
=> Fix order of (recently added) type definitions from most to least specific

README.md
.  Just a quick fix. Now "decorators are **documented** here", rather than "decorators are **document** here.
=> Quick Grammar fix to README.md

package.json, src/index.d.ts, test/ts/compile-ts.tsx, test/ts/tsconfig.json
Fix https://github.com/mobxjs/mobx/issues/665 and #97
Now you can write:
```TypeScript
@observer
class ComponentWithoutPropsAndState extends Component<void, void> {
componentDidUpdate() {
}
render() {
return (<div>Hello!</div>)
}
}
```
The solution was a simple `| void` inside index.d.ts
=> Allow Component<void, void>

README.md, package.json
With this change you can import from `native.js` by
```js
import {observe} from 'mobx-react'
``` 
React Native packager will automatically use correct file.
=> Add react-native field to package.json

src/index.d.ts
add missing `observableArrayOf` and `arrayOrObservableArrayOf` of PropTypes typing.
=> add missing typings for PropTypes

src/index.js
* ES2015 doesn't define `module`, nor `module.exports`
* Rollup's UMD wrapper doesn't pass in `module`, but it does pass in `exports`
* Since a bare variable name in JS is valid, and assumed to reference a variable in ambient/global scope, we can just use `exports` instead of `module.exports`
=> fix rollup umd runtime error re: module is not defined

src/index.js
Seems that using `exports` / `module.exports` has become tuff nowadays (https://github.com/mobxjs/mobx-react/pull/265, https://github.com/mobxjs/mobx/issues/1039)
=> Drop using module.exports for devtools

src/utils/utils.js
ref #277 
- `function() {}` has prototype
- `() => {}`(native) doesn't
And I found Babel(transform-es2015-arrow-functions) transpiles `() => {}` into `function() {}`.
=> Fix isStateless check for native arrow func

src/index.d.ts
This improves error messages because tsc refers to the last it sees.
npm run test:ts completes without complaint. Issue #270.
=> Move deprecated observer defines in front of current.

.npmignore
Now mobx-react in node_modules contain 16Mb of files like
```
...
1,1M .source.1498822720102.html
2,1M .source.1498822801644.html
1,2M .source.1498823397239.html
2,7M .source.1498824693094.html
2,7M .source.1498824814730.html
2,7M .source.1498825539594.html
2,7M .source.1498827379965.html
...
```
After remove them it use only 316Kb
=> Add usless files to .npmignore

src/observer.js
When enabling `trackComponents`, `findDOMNode` was throwing exceptions in the `try...catch` statement when used with non-DOM renderers.
I guess the empty-module behaviour changed when moving from webpack to rollup?
=> Fixed findDOMNode if-condition when used with non-DOM renderers

src/observer.js
Hello,
The Observer component renders improperly in React dev tools:
| Current | After Fix |
| -----|----|
| ![image](https://user-images.githubusercontent.com/3587605/31313103-6208df84-aba6-11e7-8147-d135f0873e7c.png) | ![image](https://user-images.githubusercontent.com/3587605/31313109-7066fc32-aba6-11e7-9855-e1efc585f6b9.png) | 
The fix was a super simple one-liner.
=> Add `displayName` to Observer component

src/index.d.ts
Not needed anymore thx to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17288 (and btw it was found that `{}` is better than `void` for props).
`void` was introduced by me in #193
=> Remove void from React.ComponentClass<P | void>

.editorconfig, .prettierrc, build-rollup.js, package.json, src/index.js, test/ErrorCatcher.js, test/context.js, test/index.js, test/inject.js, test/issue21.js, test/misc.js, test/observer.js, test/propTypes.js, test/stateless.js
* Moves the prettier config from the command line in the `prettier` npm task to `.prettierrc`
- This allows editors such as Visual Studio Code to take advantage of that file and set formatting settings appropriately.
* Also add .editorconfig for consistency
* Run the `prettier` npm task to bring the code-base formatting up to snuff
=> housekeeping: add .prettierrc, .editorconfig, and run prettier on the repo

src/index.d.ts
Hi!
Right now we have to wrap observerd value with HTML tag like:
```
const C => <Observer>{() => <div>{obser.vable}</div>}</Observer>
```
With this change you can just return observed value
```
const C => <Observer>{() => obser.vable}</Observer>
```
Thank you!
=> Update Observer component definition

.prettierignore, package.json, src/observer.js, test/context.test.js, test/index.js, test/inject.test.js, test/issue21.test.js, test/misc.test.js, test/observer.test.js, test/propTypes.test.js, test/stateless.test.js, test/transactions.test.js, yarn.lock
For some reason `husky` wasn't installed so `precommit` hook for running Prettier was never used. That leads to PR like #403 which also includes reformatting so it's harder to review.
I've run Prettier manually to fix formatting in all files. I've also added `.prettierignore` for `package.json` which is also formatted differently by Yarn on any install.
Lastly there is no need to repeat Prettier rules in for `lint-staged`, the `.prettierrc` file is respected correctly.
=> Add husky and run Prettier manually

src/observer.js, test/observer.test.js, yarn.lock
Sorry for the delay!
Fixes #363
=> Make `isObjectShallowModified` treat `NaN` equal to `NaN`

README.md
"call `useStaticRendering(true)` " in the README was ambiguous, had to look at the commit that added the function to find where it came from. Ended up being rather simple. Added an example to the README to show this.
=> Example for usage of useStaticRendering.

src/observer.js
I read through entire codebase and this seems to be spot to fix this little bug. Let me know if I'm way off so I can find the right place to patch this.
=> Fix Component displayed as 'undefined' in mobx-devtools

src/observer.js, test/issue21.test.js
Moved instrumentation of state & props to `observer` decorator.
Closes #478
=> Make props & state observable in constructor & componentWillMount

README.md
Reverts mobxjs/mobx-react#480, not applicable anymore after 5.2.1
=> Revert "added FAQ entry about reactions inside constructors"

src/observer.js, test/observer.test.js
React native Android don't have a Symbols. So, polyfill them if not exists
=> Polyfill Symbol if not exists

src/observer.js
Source issue: #500.
Just changing `createSymbol` to behave like pure function and return the same result for the same arguments.
As a result - after hot class update `.state` and `.props` refers the same underlaying objects.
Before - RHL did not work due to runtime error, as long `.state` was `undefined` for a while.
=> fix: React-Hot-Loader compatibility

src/observer.js, test/observer.test.js
When use as function, observer modifies original componentClass
It could cause `Maximum call stack size exceeded` exception after componentClass's render method got too many wrapping
It happens to me, and I create a repo to reproduce it: [https://github.com/zhangciwu/mobx-react-stack-exceeded](https://github.com/zhangciwu/mobx-react-stack-exceeded)
This PR is to fix it by extending (clone) componentClass before modifying, and keeping original class out of altering.
Also appended some test cases.
=> Fix: observer should not modify original componentClass

package.json, publish.js, yarn.lock
Basically the same that was done for mobx in https://github.com/mobxjs/mobx/pull/1735
This PR:
* removes nscript due to a dependency with fibers, a native node module that was kinda hard to compile (and actually impossible with new node versions due to compilation errors)
* fixes the publish build script so it doesn't use such dependency and uses shelljs instead
* fixes publish and build script so they work in windows as well
I think this should help new contributors get up and running faster
=> Fix windows compilation + remove nscript due to fibers dep

.travis.yml, CHANGELOG.md, README.md, build-rollup.js, package.json, src/disposeOnUnmount.js, src/index.d.ts, src/index.js, src/observer.js, src/utils/utils.js, test/disposeOnUnmount.test.js, test/no-symbol.test.js, test/observer.test.js, test/ts/compile-ts.tsx, yarn.lock
This pr adds a disposeOnUnmount as seen in https://github.com/mobxjs/mobx-react/issues/561
Closes #561
Also since I was getting weird interactions between `@observer` and this decorator (since both try to tweak componentWillUnmount) I had to adjust the way of patching lifecycle methods. The good thing is that I think it is more robust (should work with native classes, works with lifecycle methods set as arrow functions, is able to compose "mixins", etc)
Also updated dependencies
=> disposeOnUmount + new patch lifecycle method + updated deps

src/disposeOnUnmount.js, src/observer.js, src/utils/utils.js, test/disposeOnUnmount.test.js, test/patch.test.js
Fixes #581 
Basically it goes back to the "non-optimized" property definition that was at the beginning, since that one works well with inheritance, while the optimized version does not due to the reusage of variables for the instance, the prototype, the possible prototype of the prototype etc.
Either way I don't think it is a big deal since each class is patched only once, and only per class, not per instance.
=> fixing inheritance patching

README.md
#447
As mentioned, React discourages using `componentWillMount`. I think it is better not to recommend `componentWillMount` to replace `componentWillReact` even if we using a version lower than `React 16.3`.
I did not write `getDerivedStateFromProps` because it is only for new version users.
=> Replace recommendation of deprecated lifecycle

test/stateless.test.js
This is a failing test to illustrate https://github.com/mobxjs/mobx-react/issues/602. It fails with:
```
Error: Uncaught [TypeError: Cannot read property 'displayName' of undefined]
```
I'm pretty confident that this should work, and that this is the underlying issue that breaks styled components: any components that use [ref forwarding](https://reactjs.org/docs/forwarding-refs.html) can't be passed to `observe()`.
=> Create a failing test for React.forwardRef

README.md
Adds [Ignite Bowser](https://github.com/infinitered/ignite-bowser) boilerplate which uses MobX-React.
=> Adds Ignite Bowser boilerplate to README

src/utils/utils.js, test/symbol.test.js
The observer decorator created 2 Symbols for each decorated component
instead of reusing the Symbols for props and state that was previously
created
=> Cache newSymbol created Symbols

src/inject.js, src/observer.js, test/inject.test.js, test/observer.test.js
Uses the convention for HOC display names as outlined in the React documentation.
https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging
Closes #466 <- See for more details.
=> fixes HOC displayName for observer and inject

src/utils/utils.js
- Changed .keys to .getOwnPropertyNames - This gets inherited or prototype properties such as "length, prototype,..."
- Filter properties that are inherited prototypes .getPrototypeOf
- Then copy the needed keys to target
- Fixes #678 
- Example on codesandbox here https://codesandbox.io/embed/kind-gauss-pfv5q
=> Fix Object.keys with ES6 syntax as props

CHANGELOG.md, src/disposeOnUnmount.js, src/index.d.ts, src/index.js, src/observer.js, src/observerClass.js, src/utils/utils.js, test/__snapshots__/inject.test.js.snap, test/__snapshots__/observer.test.js.snap, test/observer.test.js
Proposal to revert to the classic implementation for class based observer components; by monkey patching the prototype rather than wrapping render in `<Observer>`
Fixes / affects #699, #692, #697, #702
=> Restored mixin based implementation of `observer` for class based components

src/disposeOnUnmount.js, test/disposeOnUnmount.test.js
Fixes #666 by splitting the disposer store into two separate prototype and instance stores, depending on the target parameter.
=> Separates decorator/instance usage of disposeOnUnmount

README.md, README_v5.md, test/transactions.test.js
React.render was replaced with ReactDOM.render because of https://reactjs.org/blog/2015/10/07/react-v0.14.html#two-packages-react-and-react-dom.
=> Replace React.render with ReactDOM.render in READMEs and test names

src/Provider.js
The `Provider` component has lost its descriptive name in React Dev Tools in the `6.x` version of `mobx-react`:
This PR adds it back:
=> Add the displayName static property to the Provider component

src/inject.js, src/utils/utils.js, test/index.js, test/inject.test.js
This is the proof of concept:
> Hm, looking at that code I actually wonder if that class component needs to be there. Converting a whole thing to a single functional component would yield tree-like.
https://github.com/mobxjs/mobx-react/pull/715#issuecomment-504358745
Tests are green, but I did not check it on a real production codebase.
Fixes #717 too.
=> Get rid of the redundant Injector wrapper

README.md
A couple of links in readme leading to the site I've made. This is related to #677. It's certainly too soon to call it an official site for everyone (classes are not explained much in there), but a couple of links so people can start learning won't hurt if they want.
I am a bit doubtful about documenting the `useLocalStore` and `useAsObservableSource` here in such detail. Since these are pure hooks, they are well covered on that site already. Besides, it's already bit outdated here as it doesn't cover a second argument to `useLocalStore`. What do you think? Shall I remove it?
=> Add links to documentation site

CHANGELOG.md, src/Provider.js
I think that this is an old restriction when the legacy Context API was used in `Provider`.
=> Add the ability to pass multiple children to Provider

CHANGELOG.md
Fix `CHANGELOG.md` about issue #717. This is the follow-up to https://github.com/mobxjs/mobx-react/pull/735.
=> Fix CHANGELOG.md about issue #717

src/Provider.js, test/Provider.test.js
I think that the special props handling logic in the `Provider` component is partially redundant. `key` and `ref` are special and we do not need to filter them because the props object will never contain them.
> Most props on a JSX element are passed on to the component, however, there are two special props (ref and key) which are used by React, and are thus not forwarded to the component.
https://reactjs.org/warnings/special-props.html
=> Simplify the special props handling in the Provider component

jest.setup.js, package.json, test/index.js
The advantage is that we do not need to import `test/index.js` manually in each test.
=> Setup missing React act(...) warning workaround globally in tests

test/disposeOnUnmount.test.js, test/issue21.test.js
This is the small PR with mostly cosmetic changes. I didn't know about this function when I refactored these tests.
=> Use the react-testing-library rerender function instead of render to the container

package.json, yarn.lock
It's safe to use alpha React in dev so it's easier to write tests. Also, allow for alpha in peer deps.
cc @vkrol
=> Upgrade React to 16.9 

package.json, yarn.lock
> cleanup: automatically cleanup if afterEach is detected (#430) (e2d2572), closes #428
https://github.com/testing-library/react-testing-library/releases/tag/v9.0.0
=> Upgrade react-testing-library to 9.0.2

README.md, src/Provider.js, test/Provider.test.js
https://github.com/mobxjs/mobx-react/issues/745#issuecomment-520255411
=> Clarify the reason why there is the restriction on changing the set of stores

test/issue21.test.js, test/observer.test.js
>React 16.9 does not contain breaking changes, and the old names continue to work in this release. But you will now see a warning when using any of the old names:
https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods
cWM, cWRP, cWU are deprecated, so I don't see any point in testing them.
=> Do not use deprecated lifecycle methods in tests

test/context.test.js, test/disposeOnUnmount.test.js, test/hooks.test.js, test/inject.test.js, test/issue21.test.js, test/misc.test.js, test/observer.test.js, test/propTypes.test.js, test/stateless.test.js, test/symbol.test.js, test/transactions.test.js, test/ts/compile-ts.tsx, test/ts/tsconfig.json
When working with the tests, I constantly encountered different naming and import styles in the tests. I think it's best to use the same naming style for imports. This reduces the cognitive load when working with the existing code and allows you not to think about what style to use when writing a new code.
I also want to use the same style in modules located in the `src directory`. If you don't mind, I'll do it in a separate PR.
=> Use same naming scheme and styles in imports in tests

package.json, yarn.lock
A request was made in [mobx-react-lite](https://github.com/mobxjs/mobx-react-lite/issues/170#issuecomment-525396740) to update mobx-react's dependency on mobx-react-lite to the version with support for mobx' `enforceActions` configuration support.
I believe this just this version bump is all that is needed. @FredyC is there anything else that went into 1.4.1 that could affect mobx-react? I couldn't find any release notes on 1.4.1.
=> Update mobx-react-lite dependency to support all enforceAction modes

src/Provider.js
Resolves issue #801, where `process.env` may not exist when using a `Provider` which can cause an application to crash. Simple check to ensure that the browser does not throw a reference error. This is only used in `Provider.js` to throw an error in development builds if we detect that the set of stores have changed.
=> Issue #801: Check if process.env is defined when using Provider

CHANGELOG.md, src/observerClass.js, test/observer.test.js
* Added warning for attempting to modify a component class' render function after a MobX reaction has already attached. Helps prevent memory leaks as in #797. (So mostly resolves [#797](https://github.com/mobxjs/mobx-react/issues/797))
* Added test for the above.
* Added changelog entry.
=> Warn if attempting to modify comp.render after MobX has attached

.size-limit.json, package.json
I think it's a good idea not to minify bundles. I think it's very convenient to be able to edit the module in node_modules directory and it's much easier to do when the script isn't minified. Also source maps can be disabled in dev mode for some reason and not minified bundle can help in this case.
~~I also disabled source maps generation because I don't see the point in it if we don't minify the bundles.~~
Also:
@FredyC 
> I don't think you should be providing a minified code as a main, that should be a job for the consumer
https://github.com/mobxjs/mobx-react/pull/644#issuecomment-475521989
=> Do not minify bundles

README.md
Small typo in README, "savely" should be "safely".
=> Small typo in README, savely should be safely

README.md, batchingForReactDom.js, batchingForReactNative.js, batchingOptOut.js, package.json, src/index.ts, yarn.lock
Mostly just reexport of the https://github.com/mobxjs/mobx-react-lite/pull/214.
In some distant future when 7.0 comes out, we can remove react-native specific bundle. Although it would be nice to somehow deprecate it now. Ideas?
=> Opt-in variant of batched updates

.eslintrc.js, .size-limit.json, CHANGELOG.md, jest.setup.ts, package.json, src/observer.tsx, src/observerClass.ts, test/inject.test.tsx, test/misc.test.tsx, test/observer.test.tsx, yarn.lock
Fixes #839 
-   [x] Added/updated unit tests
-   [x] Updated changelog
-   [ ] Updated `README` if applicable
=> Issue #839: Re-add isMobXReactObserver property and perform check on class components

CHANGELOG.md, src/disposeOnUnmount.ts
-   [ ] Added/updated unit tests
-   [x] Updated changelog
-   [x] Updated `README` if applicable
Fixes https://github.com/mobxjs/mobx-react/issues/725
Closed because "Solution is using react-fast-refresh". react-fast-refresh is mostly not production ready. This fix ensures compatibility.
I did not manage to recreate react-hot-loader's behavior as unit test.
=> fix disposeOnUnmount when using react-hot-loader
