index.js
test/reactiveComponent.js

fixed propTypes and defaultProps on stateless components

---

README.md

Thanks - I like this a whole bunch better then Redux - **way** less boilerplate to write. 
I am in the process of extending my [Snowflake](https://github.com/bartonhammond/snowflake) (932 Stargazers) example for a personal project and was dreading all the Redux cruft.  
I've been looking for days for a more sane approach to writing React-Native and managing the state and I think this project, Mobservable, is the perfect fit for me.  Thanks for making this available.  
I'm thinking of rewriting Snowflake and replacing Redux w/ Mobservable.  It would be an interesting comparison, I think.

Add simple react-native example

---

index.d.ts
index.js
test/stateless.js
test/ts/compile-ts.tsx

The following proptypes have been added:
- observableArray
- observableMap
- observableObject
- arrayOrObsArray
- objectOrObsObject

Added React propTypes for mobx containers

---

package.json
test/stateless.js

Fix test for observable propTypes

---

webpack.config.js

Build non-minified/non-uglified for npm

---

package.json

This one improves test output.
https://github.com/scottcorgan/tap-spec

Add tap-spec formatter

---

CHANGELOG.md
package.json

Add React as a peer dependency

---

src/index.d.ts

As described in issues #164 and #166.

Add missing TS type definitions (#164 & #166)

---

CHANGELOG.md
README.md

inject: fix method signature in docs

---

README.md
src/Provider.js
test/context.js

Add warning suppression for changed stores, and a test for it

---

package.json

I thought, the only problem was webpack 2, now the build is broken again

WIP: Fix travis build

---

package.json

add react-test-renderer as a devDependency to fix broken tests

---

src/index.d.ts
src/index.js
src/observer.js
src/utils/EventEmitter.js
test/observer.js

Global errors handler

---

README.md
src/index.d.ts
src/inject.js
src/utils/utils.js

fix #241 
I am not sure about Typescript typings because I do not use it.

Do not add ref to stateless component

---

src/observer.js

Add reference to component to reaction

---

.gitignore
build-rollup.js
empty.js
package.json
src/Provider.js
src/index.js
src/inject.js
src/observer.js

Follow up for #324, added some build script cleanups

Mijay es6 export

---

.gitignore
build-rollup.js
package.json
src/index.js

For native that should be the only bundle we create - metro bundler will do the rest; but for web and "custom" it is an opt-in.

Create an es6 bundle

---

README.md

Hi! I've spent some time trying to figure out the best way to use inject and flowtype to check the props. I haven't found *the perfect way* to do it, but at least it's a start.
I don't want to add this to the readme directly, since I still feel like it can be improved, but if we include the link, perhaps other community members will help out to find the best pattern for this.
Thanks!

typing inject with flowtype

---

src/observer.js

Discovered in https://github.com/andykog/mobx-devtools/issues/13

Fix debug name for react fiber

---

README.md

Fix example var name error

---

test/observer.test.js

Add Observer prop test suit

---

.npmignore

Fixes issue https://github.com/mobxjs/mobx-react/issues/415
Thank you for the consideration!

Adds .babelrc to .npmignore

---

README.md

Added a small sample for onError to README.md

---

src/observer.js
test/__snapshots__/misc.test.js.snap
test/misc.test.js

See https://github.com/mobxjs/mobx-react/issues/489.

Do not warn about custom shouldComponentUpdate when it is the one provided by ReactiveMixin

---

src/index.d.ts

implemetnation => implementation

fixed typo

---

README.md

https://english.stackexchange.com/questions/202832/is-there-a-difference-between-negligible-and-neglectable

neglectable to negligible

---

src/utils/utils.js
test/disposeOnUnmount.test.js

Fixes #579 by making sure recursive calls to the function are stopped

fix recursive calls for patching

---

src/utils/utils.js
test/patch.test.js

Fixed #579 
hopefully for the last time :)
with unit tests

fix patching again

---

package.json

ref:  https://github.com/jsdom/jsdom/issues/2304

test: add testURL to fix jsdom SecurityError

---

README.md

https://github.com/mobxjs/mobx-react/issues/700
I was confused when reading the changelog re; the automatic applying of `memo`

Attempt to clarify the use of observer

---

CHANGELOG.md
src/utils/utils.js

Fix IE 11 compatiblity

---

README.md
package.json
test/__snapshots__/inject.test.js.snap
test/inject.test.js
test/issue21.test.js
test/misc.test.js
test/observer.test.js
test/stateless.test.js
test/transactions.test.js
test/ts/compile-ts.tsx
yarn.lock

Depends on #703 
This PR removes the usage of create-react-class

Test cleanup

---

test/__snapshots__/inject.test.js.snap

It fixes the build https://circleci.com/gh/mobxjs/mobx-react/102.
Related PR: https://github.com/mobxjs/mobx-react/pull/711.

Update the Jest snapshot after changing the name of the Provider component

---

package.json
test/index.js
test/inject.test.js
test/observer.test.js
test/stateless.test.js
test/symbol.test.js
test/transactions.test.js

From https://github.com/mobxjs/mobx-react/pull/720#issue-292091888:
> I've also installed @testing-library/react and jest-mock-console to start modernizing tests slightly. 
This is the first part of conversion of the tests to `react-testing-library`.

Use react-testing-library Part 1

---

test/disposeOnUnmount.test.js
test/inject.test.js
test/issue21.test.js
test/observer.test.js
test/stateless.test.js
test/symbol.test.js
test/transactions.test.js

This is the follow up to https://github.com/mobxjs/mobx-react/pull/724.

Use react-testing-library Part 2

---

package.json
test/misc.test.js
test/observer.test.js
yarn.lock

This is the follow up to https://github.com/mobxjs/mobx-react/pull/728.

Use react-testing-library Part 3

---

test/index.js
test/observer.test.js

This is the follow up to https://github.com/mobxjs/mobx-react/pull/731.

Use react-testing-library Part 4

---

src/Provider.js

From https://github.com/mobxjs/mobx-react/pull/737#discussion_r309406735:
> And you can rewrite it to FC when you are it :D

Rewrite the Provider component to function component

---

src/Provider.js

Simplify the Provider component by using object destructuring (thanks to @urugator).
https://github.com/mobxjs/mobx-react/issues/745#issuecomment-518415498

Simplify the Provider component by using object destructuring

---

package.json
test/__snapshots__/observer.test.js.snap
test/__snapshots__/stateless.test.js.snap
test/misc.test.js
test/observer.test.js
test/stateless.test.js
yarn.lock

This is the follow-up to https://github.com/mobxjs/mobx-react/pull/766.

Use react-testing-library instead of react-test-renderer part 2

---

publish.js

Revert "Update publish.js"

---

src/observer.tsx
src/propTypes.ts
src/types/IReactComponent.ts

Resolves #822.  Fallout from JavaScript to TypeScript conversion.  I suppose I may run into more issues as a work my way through the tests.  I will have a better idea by the end of the day.

Issue #822: resolve signature of observer decorator

---

CHANGELOG.md
README.md
src/observer.tsx

Updated the changelog in response to #838.  Should we update the README as well in better detail?
-   [x] Updated changelog
-   [x] Updated `README` .....if applicable?

Issue #838: Clarify use of PureComponent and memo in changelog

---

README.md

-   [ ] ~~Added/updated unit tests~~
-   [ ] ~~Updated changelog~~
-   [x] Updated `README` if applicable

Fix markdown formatting issue

---

README.md
jest.setup.ts
package.json
src/index.ts
test/inject.test.tsx
test/issue21.test.tsx
test/observer.test.tsx
yarn.lock

-   [ ] Added/updated unit tests
-   [ ] Updated changelog
-   [ ] Updated `README` if applicable

Initial MobX 6 migration
